nname: Hank Quinlan, Horrible Cop
markdown: kramdown

permalink: /blog/:title

collections:
  definitions:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "definitions"
    values:
      layout: "definition"
